### ISSUE TITLE
LdapIdentityStore: No group returned if useForExpression is specified

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#121]
@LdapIdentityStoreDefinition(
		url = "ldap://localhost:11389/",
		callerBaseDn = "ou=caller,dc=securityapi,dc=net",
		groupSearchBase  = "ou=group,dc=securityapi,dc=net",
		useFor={ValidationType.VALIDATE},
		priority=100,
   	        useForExpression="${configBean.useforBoth}"
)

And in ConfigBean, it contains below variables.
ValidationType[] useforBoth = {ValidationType.VALIDATE, ValidationType.PROVIDE_GROUPS};

No groups returned when request with valid user/pwd.

**Comment by ggam** [comment]
Thanks for the report! I've created #122. Should be merged soon.
