### ISSUE TITLE
Does Pbkdf2PasswordHashImpl work or not now?

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#134]
https://asecuritysite.com/encryption/PBKDF2z
I could generate a hash by using above tool. But it requires salt paramemeter. 

After checking https://github.com/javaee/security-soteria/blob/master/impl/src/main/java/org/glassfish/soteria/identitystores/hash/Pbkdf2PasswordHashImpl.java, it seems the salt is generated randomly. 

Here I have two questions
1)  Does Pbkdf2PasswordHashImpl work or not now?
2)  Could I use https://asecuritysite.com/encryption/PBKDF2z tool to generate a hash string and store it in database password, and then do validation use Pbkdf2PasswordHashImpl?

Thanks!

**Comment by rdebusscher** [comment]
Hi,

Indeed, the verify method is missing the salt value which needs to be used for verification of the (hashed)password.

**Comment by arjantijms** [comment]
At any length a new test for a DB with hashed data (possibly multiple variants) should be added.

**Comment by rdebusscher** [comment]
Sorry, forget my previous comment. I was too fast and should have looked at the code first.

Have a look at the Pbkdf2PasswordHashImpl class within Soteria, especially the EncodedPasswordHash inner class.

There you can see that the 'hashed password' contains more information than just the hash.

`algorithm:iterations:Base64(salt):Base64(hash)`

So when you convert the salt from HEX to base64 used on that website, it should work.

**Comment by ggam** [comment]
@wxwesther you can use the generate method to create the password and then store it in the database

**Comment by wmhopkins** [comment]
Yes, the `generate()` method on `Pbkdf2PasswordHashImpl` should be used to generate password hashes for testing purposes. It may or may not be possible to verify the result using the referenced web site, as it's not specific about the PBKDF2 flavor it's using (i.e., it doesn't specify an HMAC algorithm that it's using).

**Comment by wxwesther** [comment]
Got it. Thanks all for your answer!
