### ISSUE TITLE
DatabaseIdentityStore:NPE appears when use Pbkdf2PasswordHash

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#135]
```
@DatabaseIdentityStoreDefinition(	    
		dataSourceLookup="jdbc/securityAPIDB",
	    callerQuery="select password from caller where name = ?",
	    groupsQuery="select group_name from caller_groups where caller_name = ?"
)

@DatabaseIdentityStoreDefinition(	    
		dataSourceLookup="jdbc/securityAPIDB",
	    callerQuery="select password from caller where name = ?",
	    groupsQuery="select group_name from caller_groups where caller_name = ?",
	    hashAlgorithm = Pbkdf2PasswordHash.class,
	    hashAlgorithmParameters = {
			"Pbkdf2PasswordHash.Iterations=2048", 
			"Pbkdf2PasswordHash.SaltSizeBytes=32", 
			"Pbkdf2PasswordHash.KeySizeBytes=32"
			}
)
```

No matter use default setting for hashAlgorithm, or specify hashAlgorithm and hashAlgorithmParameters, Null pointer exception always appears.

```
[2017-07-26T21:46:11.492-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=27 _ThreadName=Thread-9] [timeMillis: 1501130771492] [levelValue: 1000] [[
  java.lang.NullPointerException                                                                                                                        
        at org.glassfish.soteria.identitystores.DatabaseIdentityStore.<init>(DatabaseIdentityStore.java:85)                                             
        at org.glassfish.soteria.cdi.CdiExtension.lambda$null$2(CdiExtension.java:137)                                                                  
        at org.glassfish.soteria.cdi.CdiProducer.create(CdiProducer.java:103)                                                                           
        at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)                                                                          
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)                    
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)                                                                       
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)                                                       
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:99)                                                              
        at org.jboss.weld.proxies.IdentityStore$635317201$Proxy$_$$_WeldClientProxy.validationTypes(Unknown Source)                                     
        at org.glassfish.soteria.cdi.DefaultIdentityStoreHandler.lambda$init$0(DefaultIdentityStoreHandler.java:75)       
```

**Comment by rdebusscher** [comment]
Hi @wxwesther,

Can you confirm that this statement returns null?
`hashAlgorithm = getBeanReference(dataBaseIdentityStoreDefinition.hashAlgorithm());`

It is the line just before the NPE.

I assume you tested it with GF5.
At least with JBoss 10 it is working.

So could be a CDI issue.

**Comment by arjantijms** [comment]
The tests use the identity algorithm if I'm not mistaken and those at least passed on all 4 servers tested.

**Comment by wxwesther** [comment]
Hi rdebusscher,

Yes, I tested glassfish5-m10 with the latest API and RI packages. Did I mistake anything?

Thanks
Iris

**Comment by wmhopkins** [comment]
@wxwesther -- Have you tried the latest RI snapshot build? The bean annotation was changed from @Application to @Dependent, which probably affects initialization. If it still doesn't work, can you try removing the hashAlgorithmParameters and see if that helps? The values you're supplying are the same as the defaults, so there would be no change in expected behavior, but the result may tell us whether the problem is related to processing properties or not.

**Comment by wxwesther** [comment]
Hi Will,
I got the latest snapshot from below,and same error appears.
https://maven.java.net/content/repositories/snapshots/javax/security/enterprise/javax.security.enterprise-api/1.0-b10-SNAPSHOT/javax.security.enterprise-api-1.0-b10-20170727.210454-5.jar
https://maven.java.net/content/repositories/snapshots/org/glassfish/soteria/javax.security.enterprise/1.0-b11-SNAPSHOT/javax.security.enterprise-1.0-b11-20170727.223321-5.jar

Same error appears without hashAlgorithmParameters like below:
@DatabaseIdentityStoreDefinition(	    
		dataSourceLookup="jdbc/securityAPIDB",
	    callerQuery="select password from caller where name = ?",
	    groupsQuery="select group_name from caller_groups where caller_name = ?",
           hashAlgorithm = Pbkdf2PasswordHash.class
)

**Comment by ggam** [comment]
> The tests use the identity algorithm if I'm not mistaken and those at least passed on all 4 servers tested.

@arjantijms Seems like the only database test is still using plaintext passwords: https://github.com/javaee/security-soteria/blob/master/test/app-db/src/main/java/org/glassfish/soteria/test/ApplicationConfig.java#L50

I'm taking a look at this. I'll try to fix it and update the test.

**Comment by rdebusscher** [comment]
@ggam 

But the main usage of Soteria is that it is deployed as "module" on the server. And there the beans.xml doesn't matter. That is also the usecase which is described by @wxwesther since he was using GF 5-m10

By the way, when no beans.xml is available but there is a class found with a 'bean definition' it is an implicit bean archive.

The issue is that the Pbkdf2PasswordHashImpl class is not registered within the CDI extension.
org.glassfish.soteria.cdi.CdiExtension#register()

I'll prepare a PR.

**Comment by ggam** [comment]
Manually registering the class is maybe a better option since it will
prevent unneeded classes to be available to the deployments (which will
probably be addressed by Java 9 anyway).

But then, if the jar is already a bean archive, why its beans are not
already detected? I didn't find any package-info.java with @Veto annotation.

**Comment by ggam** [comment]
> By the way, when no beans.xml is available but there is a class found with a 'bean definition' it is an implicit bean archive.

Reading the spec, I'm not really sure about that (http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bean_archive):

> An archive which:
> *  contains a beans.xml file with the bean-discovery-mode of none, or,
> * contains an extension and no beans.xml file
>
> is not a bean archive.

But it also says about extensions:
> An extension may be deployed in any archive, including those that are not bean archives.
