### ISSUE TITLE
Application provided HttpAuthenticationMechanism takes precedence

### ISSUE THREAD

**Issue by ggam** [javaee/security-soteria#146]
Spec section 2.3:
> If    the    container    does    not    override    the    application,    it    MUST    place    in    service    any HttpAuthenticationMechanism that is provided, either directly or via annotation, by the application.

Currently Soteria is deploying correctly and failing at runtime when the application provides a custom HttpAuthenticationMechanism and also a built-in one is enabled.

**Comment by arjantijms** [comment]
This should probably be easy to trigger a deployment failure earlier on. The scope here doesn't matter, but just the fact that two definitions are found (by e.g. the extension in Soteria) should be enough.

**Comment by ggam** [comment]
Thanks for the input. I I read it, the application should stil deploy but ignoring the built-in mechanism, although it has been requested by the user...

Is my interpretation wrong, or should the text be changed?

**Comment by ggam** [comment]
The change I've done: https://github.com/javaee/security-soteria/compare/master...ggam:authmech-priority

**Comment by ggam** [comment]
@arjantijms Reading it again, I see you're right. It was misinterpretation on my side: both beans would be enabled by the user, so "the results are undefined" (which will mean deployment error in the case of Soteria. I'll prepare a new PR.
