### ISSUE TITLE
Container CallerPrincipal gets lost if an application caller principal is provided in the application

### ISSUE THREAD

**Issue by vinayvishal** [javaee/security-soteria#155]
In case of Custom `HttpAuthenticationMechanism` bundled in the application, in `HttpAuthenticationMechanism#validate()` method, post a call to `IdentityStoreHandler#validate()` method, if application provider chooses to provide application caller principal by passing a custom principal in HttpMessageContext.notifyContainerAboutLogin()`, if application provider doesn't add container caller principal in the client subject, the container caller principal kind of gets lost.

#### `TestAuthenticationMechanism` that will cause a null to return when `SecurityContext#getCallerPrincipal()` is called.
```java
@RequestScoped
public class TestAuthenticationMechanism implements HttpAuthenticationMechanism {

    @Inject
    private IdentityStoreHandler identityStoreHandler;

    @Override
        public AuthenticationStatus validateRequest(HttpServletRequest request, HttpServletResponse response, HttpMessageContext httpMessageContext) throws AuthenticationException {

        String name = request.getParameter("name");
        String password = request.getParameter("password");

        if (name != null && password != null) {

            CredentialValidationResult result = identityStoreHandler.validate(
                    new UsernamePasswordCredential(name, password));

            if (result.getStatus() == VALID) {

            AuthenticationStatus authenticationStatus = httpMessageContext.notifyContainerAboutLogin(new MyPrincipal(name), result                      .getCallerGroups());
                return authenticationStatus;
            } else {
                return httpMessageContext.responseUnauthorized();
            }
        
private class MyPrincipal implements Principal {
        String name;

        public MyPrincipal(String name) {
            this.name = name;
        }

        @Override
        public String getName() {
            return name;
        }
    }
}
```
In the above example, when inside the servlet, when `SecurityContext.getCallerPrincipal()` is called, since there is no container principal available in the subject, `SecurityContext.getCallerPrincipal()` returns null when internally through `CallerDetailsResolver#getCallerPrincipal()` , it tries to look for a principal having the class name as `javax.security.enterprise.CallerPrincipal`.

#### `TestAuthenticationMechanism` that will return correct container caller principal when `SecurityContext#getCallerPrincipal()` is called.

In this case container caller principal is being added before authentication status is being returned in the validate method.

`httpMessageContext.getClientSubject().getPrincipals().add(result.getCallerPrincipal());`

```java
@RequestScoped
public class TestAuthenticationMechanism implements HttpAuthenticationMechanism {

    @Inject
    private IdentityStoreHandler identityStoreHandler;

    @Override
        public AuthenticationStatus validateRequest(HttpServletRequest request, HttpServletResponse response, HttpMessageContext httpMessageContext) throws AuthenticationException {

        String name = request.getParameter("name");
        String password = request.getParameter("password");

        if (name != null && password != null) {

            CredentialValidationResult result = identityStoreHandler.validate(
                    new UsernamePasswordCredential(name, password));

            if (result.getStatus() == VALID) {

            AuthenticationStatus authenticationStatus = httpMessageContext.notifyContainerAboutLogin(new MyPrincipal(name), result                      .getCallerGroups());
httpMessageContext.getClientSubject().getPrincipals().add(result.getCallerPrincipal());
                return authenticationStatus;
            } else {
                return httpMessageContext.responseUnauthorized();
            }
        
private class MyPrincipal implements Principal {
        String name;

        public MyPrincipal(String name) {
            this.name = name;
        }

        @Override
        public String getName() {
            return name;
        }
    }
}
```
In the above example, since `TestAuthenticationMechanism`  also adds the container caller principal in the subject before returning the authorization status, inside the servlet, when `SecurityContext.getCallerPrincipal()` is called, since now container caller principal exists in the subject (of type `javax.security.enterprise.CallerPrincipal`), `SecurityContext.getCallerPrincipal()` manages to find the container caller principal internally through `CallerDetailsResolver#getCallerPrincipal()` , when it tries to look for a principal with class name as `javax.security.enterprise.CallerPrincipal`.

In the scenario when `TestAuthenticationMechanism` adds container caller principal explicitly when an application caller principal is provided, if the application provider chooses to provide an application caller principal which extends from `javax.security.enterprise.CallerPrincipal`, when `SecurityContext#getCallerPrincipal()` is called, the container will still be able to find the container caller principal since in subject there is only one principal with class name `javax.security.enterprise.CallerPrincipal`.

However, if application provider , instead of extending from `CallerPrincipal`, chooses to use `javax.security.enterprise.CallerPrincipal` as application caller principal, though in this scenario, both container caller principal and application caller principal are present in the subject, they happen to have same class name and hence there is no guarantee that that principal returned when `SecurityContext#getCallerPrincipal()` is called will actually be container caller principal.

From the spec:

> ### 1.2.2 Caller Principal Types
> Because both containers and applications can have legitimate requirements for specific Principal types to represent a caller, and those types may differ, it MUST be possible for the container to establish both the container’s and the application’s caller principal as the caller’s identity; for example, by including both in a Subject representing the caller.

since it is a **MUST** for the container to establish both the container's and the application caller principal as the caller's identity (e.g by including both in the `Subject` representing the caller) , is adding container caller principal in application provided authentication mechanism is the intented way of doing so?

If not, should we probably look for enhancing `HttpMessageContext` interface by defining one more flavor of `notifyContainerAboutLogin()` method which takes both `Principal` types as parameter.

**Comment by vinayvishal** [comment]
Relates to #133

**Comment by wmhopkins** [comment]
As discussed in my reply to your email, I believe this is essentially a duplicate of #133 w.r.t. the first issue mentioned, and working as designed w.r.t. the second issue mentioned.

The failure to return a principal from `getCallerPrincipal()` in the first instance is a problem with `getCallerPrincipal()`, not a problem with the principals in the `Subject`.

In the second case, the application (HAM) chose to put an additional principal in the `Subject`. That is legal, but the container has no control over that, and no obligation to enforce any constraints on the application. The fact that this resulted in a `CallerPrincipal` being in the `Subject`, and therefore returned by `getCallerPrincipal()` is incidental.

Also, note that it must be *possible* for the container to establish two principals. That does not mean that the container is obligated to maintain two principals in any given case, it is only required that the application be able to specify a principal that it wants. It's up to the container whether it will insist on also having its own representation of the caller principal, and the internal representation in the `Subject` is also up to the container.

Closing this as a duplicate of #133.

**Comment by vinayvishal** [comment]
I spent some more time on this, I still feel we probably are missing the point or may be my understanding of container caller principal is not correct. 
The `CallerPrincipal` I am referring to is basically the `Principal` returned by `DefaultIdentityStoreHandler`. It is this principal, which gets lots in the process when in custom `HttpAuthenticationMechanism` , the application provider chooses to provide its own `Principal`. 

If this `Principal` (Lets call it `AppPrincipal`) implements `java.security.Principal` and not `javax.security.enterprise.CallerPrincipal`, then in the `SubjectParser`, it falls to following code block, where a call to `HttpServletRequest.getUserPrincipal()` returns an instance of `WebPrincipal` which is again just a wrapper around application provided caller principal `AppPrincipal`.
```java
try {
return CDI.current().select(HttpServletRequest.class).get().getUserPrincipal();
} catch (Exception e) {
// Not inside an HttpServletRequest
}
```
It should also be noted that though `SubjectParser` does have a `switch` `case` for `org.glassfish.security.common.PrincipalImpl`, it will never fall in this block because Glassfish will create an instance of this principal to represent caller principal only when `CallerPrincipalCallback` gets a `String` representation of the principal and though one of the flavors of `HttpMessageContextImpl#notifyContainerAboutLogin` does take a string value for principal, however before calling JASPIC, it wraps it `javax.security.enterprise.CallerPrincipal`.

**`CallerPrincipalCallback`**
```java
   public CallerPrincipalCallback(Subject s, String n) { 
	subject = s;
	principal = null;
        name = n;
    }
```
**`HttpMessageContextImpl`**
```java
/* (non-Javadoc)
     * @see javax.security.authenticationmechanism.http.HttpMessageContext#notifyContainerAboutLogin(java.lang.String, java.util.Set)
     */
    @Override
    public AuthenticationStatus notifyContainerAboutLogin(String callerName, Set<String> groups) {
        CallerPrincipal callerPrincipal = null;
        if (callerName != null) {
            callerPrincipal = new CallerPrincipal(callerName); // TODO: or store username separately?
        }

        return notifyContainerAboutLogin(callerPrincipal, groups);
    }
```
**`BaseContainerCallbackHandler`**
```java
if (principal == null) {
            if (cpCallback.getName() != null) {
                if (isCertRealm) {
                    principal = new X500Principal(cpCallback.getName());
                } else {
                    principal = new PrincipalImpl(cpCallback.getName());
                }
            } else {
                // 196 unauthenticated caller principal
                principal = SecurityContext.getDefaultCallerPrincipal();
            }
        }
```
In a nutshell, we essentially are losing the `CallerPrincipal` returned as part of `CredentialValidationResult` by `IdentityStoreHandler` whenever an application chooses to provide its own caller principal. My query would be then, is it okay if this doesn't get added in `Subject`, if an application caller principal has been provided when a call to `HttpMessageContext#notifyContainerAboutLogin` is made? 

javadoc for `HttpMessageContext` mentions this:

> **notifyContainerAboutLogin**
> ---
> ```java
> AuthenticationStatus notifyContainerAboutLogin(Principal principal, Set<String> groups)
> ```
>                                               
> Asks the container to register the given caller principal and groups in order to make them available to the application for use with `SecurityContext.isCallerInRole(String)` etc.
>
> Note that this call may result in the container establishing two caller principals to represent the caller's identity -- **the `Principal` provided here as the principal parameter, and a second principal used as the container's representation of the caller identity. A second principal is added only if the container uses a different Principal type to represent the caller. If the types are the same, only one Principal is added.**
>
> If a second principal is added, the value returned by Principal.getName() will be the same for both principals.
> 
> When two principals are added, the container's caller principal is returned from `SecurityContext.getCallerPrincipal()`, and the principal supplied here as a parameter can be retrieved using `SecurityContext.getPrincipalsByType(Class)`. 
>
> When only one is added, it is returned by `SecurityContext.getCallerPrincipal()`.

At present, both `SecurityContext.getCallerPrincipal()` and `SecurityContext.getPrincipalsByType(Class)` points to the principal supplied in `notifyContainerAboutLogin` method, its just that we get the principal supplied here wrapped in a `WebPrincipal` when `SecurityContext.getCallerPrincipal()` is called but essentially they both are pointing to same instance.

**Comment by wmhopkins** [comment]
@vinayvishal -- per our discussion today, I think you are clear on the intended behavior for caller principal vs. application principal -- they may be distinct principals, and that must be allowed for platforms that need or want to do this, but it's also legitimate to have just one principal, if that principal can serve as both the container principal and the application principal.

I am preparing a PR to address the issue with `notifyContainerAboutLogin()` converting a `String callerName` argument to a `callerPrincipal`, which it shouldn't do.
