### ISSUE TITLE
SecurityContext.getCallerPrincipal() doesn't return correct value for Anonymous in EJB container

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-soteria#158]
The fix for #133 (see PR #140) is incomplete. It will find the correct principal more often, but in the case of EJB it needs to be able to determine whether a non-null principal name represents and authenticated caller or the anonymous user. Currently the code checks for null/empty principal name, but not for the GF- (or other platform-) specific anonymous principal name.

**Comment by ggam** [comment]
I'm aware #140 lacked the EJB check. I'll verify what's the returned value on GlassFish and make a new PR.

I've self-assigned this issue.

**Comment by ggam** [comment]
I've just verified that GlassFish returns "ANONYMOUS" in case of unauthenticated EJB

**Comment by wmhopkins** [comment]
Sounds good -- thanks, Guillermo.

**Comment by ggam** [comment]
Just for reference, here are the returned names on each supported server:

GlassFish: ANONYMOUS
WildFly: anonymous
TomEE: guest
Liberty: UNAUTHENTICATED
WebLogic: <anonymous>

**Comment by wmhopkins** [comment]
Excellent, really good to have that.
