### ISSUE TITLE
Just to confirm, in Pbkdf2PasswordHashImpl, the configured parameters just used in generate, not verify

### ISSUE THREAD

**Issue by zjmtlab** [javaee/security-soteria#160]
I found in Pbkdf2PasswordHashImpl, the configured parameters, like configuredAlgorithm and configuredIterations ...  Just be used when generate encoded password, when decode the password, it not used the configured parameters in class. It will use the parameters which stored with password.

I just want to confirm that is what we expected. Thanks!

**Comment by ggam** [comment]
Yes, that seems to be the idea, as per @wmhopkins comment on https://github.com/javaee/security-soteria/pull/152#issuecomment-320544847

The call to initialize on the db test is not needed and I made a PR to remove it (https://github.com/javaee/security-soteria/pull/161)

**Comment by wmhopkins** [comment]
Yes, that is the expected behavior, as documented (I believe) in javadoc for Pbkdf2PasswordHash.

**Comment by ggam** [comment]
Yes, it's documented on the JavaDoc: https://github.com/javaee/security-api/blob/787e6a0a7794239b04bfd3d1acb444a3f3b63616/src/main/java/javax/security/enterprise/identitystore/Pbkdf2PasswordHash.java#L71
