### ISSUE TITLE
cleanSubject doesn't work after rememberMe test case when SecurityManager enabled

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#174]
Pre-condition:
============================
1. Enable SecurityManager by below command, and stop/start GF server 
./asadmin create-jvm-options –Djava.security.manager

2.Issue steps
============================
1. Run rememberMe test cases
    __go to $TS_HOME/src/com/sun/ts/tests/securityapi/ham/rememberme
   __run below command 
       ant -Dreport.dir=$TS_HOME/src/com/sun/ts/tests/report -Dwork.dir=$TS_HOME/src/com/sun/ts/tests/work runclient
2. Run cleanSubject test case. Failed
   __go to $TS_HOME/src/com/sun/ts/tests/securityapi/ham/workflow/cleansubject
   __run below command 
         ant -Dreport.dir=$TS_HOME/src/com/sun/ts/tests/report -Dwork.dir=$TS_HOME/src/com/sun/ts/tests/work runclient
3. stop/start Glassfish server
4. Run cleanSubject test case. Succeed
5.  Run rememberMe test cases
6. Run cleanSubject test case. Failed

Comment:
===========
1. When Fail to run cleanSubject test case, there is no exception, only the subject is not cleaned.
But since rememberMe test case and cleanSubject are in different application, then I don't think the rememberMe setting in one app would do effect to cleanSubject in another application.

2. cleanSubject test case always passed when secureManager is disabled.

**Comment by wmhopkins** [comment]
Iris, I can't look at this without a reproducible test case that I can build -- I do not have the TCK environment set up, and the instructions for doing so are complex and require me to work on my hosted Linux box which is not currently have recent versions of git, mvn, etc.

(This would be easier if the tck branch in git were pushed to the GF repo, so I could sync it from my laptop.)

Can you reproduce this behavior in a small test case? Or give me access to a host where this is reproducible?

**Comment by wxwesther** [comment]
Hi Will, You can use my box, VNC is slc03nsu:1/welcome
Please ping me when you want to use my box.

**Comment by wmhopkins** [comment]
It seems likely this is due to the behavior of the `RememberMeInterceptor`, which intercepts `cleanSubject()` and then does:
```
rememberMeIdentityStore.removeLoginToken(rememberMeCookie.getValue());
```
What it does NOT do is continue on to call `cleanSubject()`.

@arjantijms -- I think the interceptor should call `invocationContext.proceed()` to delegate to the `cleanSubject()` method of the underlying HAM, after removing the login token. Do you agree Unfortunately doesn't document this, but we can at least make the RI do the right thing and update the spec when we release it again. Please comment; meanwhile I'll prepare a change.

**Comment by wmhopkins** [comment]
Fix delivered -- please retest.
