### ISSUE TITLE
RememberMe and LoginToContinue interceptors fail to get bindings for CDI 2.0 dynamic interceptor

### ISSUE THREAD

**Issue by arjantijms** [javaee/security-soteria#179]
The interceptors backing `@RememberMe` and `@LoginToContinue` need access to these annotation instances (called interceptor bindings) to read the attributes from.

This works as intended when the annotation is statically applied to a bean, but does not work if its dynamically applied as per the new CDI 2.0 interception factory.

As the spec just mentions that the attributes should be used, but not *how* these should be obtained, this should be relatively easy to fix using implementation (RI) code only. No spec (text or javadoc) update is needed.

**Comment by arjantijms** [comment]
Fixed in the smallest most low impact way for just the RI. When we introduce/refactor the implementation specific SPI (post 1.0), this part should probably have its own mini SPI as well.

**Comment by wmhopkins** [comment]
@arjantijms -- Can you explain this a little further for me? When you say the annotation doesn't work if the annotation is, "dynamically applied as per the new CDI 2.0 interception factory", is that a function of the latest CDI runtime, or is that a function of the application choosing to use a new feature of CDI 2.0?

Also, the change you made looks reasonable, but to make sure I understand the change you made, can you confirm that this code:
```
invocationContext.getContextData().get("org.jboss.weld.interceptor.bindings");
```
Can only return instances of, e.g., `LoginToContinue`, that are bound to the specific interceptor instance that is looking them up?

**Comment by arjantijms** [comment]
It's the new feature in CDI 2.0 where an interceptor can be dynamically added. Before CDI 2.0 these were always statically present on a class.

For an example of dynamically adding an interceptor, see: 

https://github.com/javaee-samples/javaee8-samples/blob/master/cdi/interception-factory/src/main/java/org/javaee8/cdi/interception/factory/MyGreetingProducer.java#L34

So the old method of inspecting the target class no longer works in all situations, since that target class no doesn't necessarily have to have the annotation physically on it.

It's a function of the application choosing to use a new CDI 2.0 feature. There's no situation that I know of where existing applications (coded against the CDI 1.2 APIs) will trigger this.

The RI provides a solution for this by putting all these annotations (called "interceptor bindings") independent of where they originate from in the existing context data map under the key "org.jboss.weld.interceptor.bindings".

So indeed:

```
invocationContext.getContextData().get("org.jboss.weld.interceptor.bindings");
```

Returns the interceptor bindings associated with the current interceptor instance (the `invocationContext` object is part of that particular instance).

**Comment by wmhopkins** [comment]
Thanks, @arjantijms .
