### ISSUE TITLE
SecurityException while getting unwrapped request

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-soteria#186]
From @zjmtlab :

About the issue 9:
```
  Exception2: (No stacktrace in server)
   [2017-08-20T21:53:43.442-0700] [glassfish 5.0] [INFO] [] [javax.enterprise.system.core.security] [tid: _ThreadID=31 _ThreadName=http-listener-1(5)] [timeMillis: 1503291223442] [levelValue: 800] [[
  JACC Policy Provider: Failed Permission Check, context(securityapi_ham_autoapplysession_web/securityapi_ham_autoapplysession_web)- permission(("java.security.SecurityPermission" "getUnwrappedCoyoteRequest"))]]
```
I found below code in Soteria AutoApplySessionInterceptor.java, since the `getUnwrappedCoyoteRequest` method in GF will invoke `AccessController.checkPermission()`. So I think maybe this Soteria code should add `doPrivileged` block.
```
    // TEMP workaround for https://github.com/payara/Payara/issues/290#issuecomment-207136005
    // TODO: THIS HAS TO BE FIXED AND SHOULD NOT STAY IN THE CODE LIKE THIS
    private Principal getPrincipal(HttpServletRequest request) {

        try {
            ELProcessor elProcessor = new ELProcessor();
            elProcessor.defineBean("request", request);
            return (Principal) elProcessor.eval("request.getUnwrappedCoyoteRequest().getUserPrincipal()");
        } catch (Exception e) {
            // ignore
        }

        return request.getUserPrincipal();

    }
```

**Comment by arjantijms** [comment]
As per the comment, that entire section might not even be needed anymore. It was fixed in Payara, but I'm not 100% sure if it was fixed in GlassFish as well.

**Comment by arjantijms** [comment]
I just did a quick check, and at least for Payara that entire code fragment isn't needed anymore, meaning it can be reduced to:

```java
private Principal getPrincipal(HttpServletRequest request) {
    return request.getUserPrincipal();
}
```

**Comment by wmhopkins** [comment]
I'll recode it that way.

**Comment by wmhopkins** [comment]
@arjantijms -- where would I look to verify that this is fixed in Glassfish? I'm not clear on whether the desired behavior is that the principal returned should be wrapped, or should not be wrapped, or if the fix is actually in some bit of code somewhere that looks up the correct session based on the principal returned by `getUserPrincipal()` ... ?
