### ISSUE TITLE
Soteria 1.0 has API 1.1-b01-SNAPSHOT dependency

### ISSUE THREAD

**Issue by keilw** [javaee/security-soteria#206]
Guys, 

Someone messed up the POMs of Soteria 1.0 rather badly 👎 

Not sure, how this remained unnoticed since 1.0 went out in Sep 2017, probably because everyone keeps building in the "Public Cloud" where the Snapshot repo with Security API 1.1-b01-SNAPSHOT can be accessed.

However, it is grossly wrong to reference a preview of a not even released 1.1 API with the Final release.

I tried to use Soteria with Glassfish Payara/4 and I must not use Java EE 8 API because the client uses Java EE 7 for now. Soteria 1.0 would have been OK but because all builds happen behind a firewall, it cannot be used like that.

**Comment by arjantijms** [comment]
Doesn't look too good indeed. To be clear, it's this location that defined the version number:

https://github.com/javaee/security-soteria/blob/1.0/pom.xml#L89

And it's used as API dependency here:

https://github.com/javaee/security-soteria/blob/1.0/impl/pom.xml#L68

**Comment by keilw** [comment]
@wmhopkins accidentially applied some 1.1 changes in pushes like https://github.com/javaee/security-soteria/commit/63d48ae91e7745cc8ec134fac1bb57d823f74de6#diff-600376dffeb79835ede4a0b285078036 before 1.0 was actually deployed to Sonatype.

```xml
        <spec_impl_version>1.1-b01-SNAPSHOT</spec_impl_version>
        <api_dependency_version>${spec_impl_version}</api_dependency_version>
        <impl_version>1.0</impl_version>
```
shows, that `spec_impl_version` was increased and prematurely used as api_dependency_version instead of using `impl_version` or leaving the value of `api_dependency_version `at 1.0 till a new API is actually out.

@yaminikb As you just merged something could you help fix this and release an actual Soteria 1.0.1 or 1.1 (an emergency Patch, not a MR, the API is not affected) to MavenCentral?

**Comment by ashri** [comment]
Just to note, this is the same issue as mentioned in #193

**Comment by keilw** [comment]
Thanks, then it's even worse nobody picked it up since, but I will try those remedies in the POM. Can close this one as duplicate though.
