### ISSUE TITLE
Test for custom identity store handler issues

### ISSUE THREAD

**Issue by rdebusscher** [javaee/security-soteria#62]
The code within app-custom-identity-store-handler (test module) is invalid.

The method org.glassfish.soteria.test.BlackListedIdentityStore#validate has invalid argument and is thus never called.

This makes the test useless.

**Comment by rdebusscher** [comment]
The custom identity store handler was not generic enough. Meaning that an INVALID validationResult could be overruled by the next VALID result (which was never the case for the test cases but if someone should take inspiration, it rather be correct)

**Comment by arjantijms** [comment]
Would be good to fix ;)

Btw, perhaps the groups coming from the LDAP store could be renamed with say an "LDAP-" prefix, so it's a bit clearer for the test where roles come from?

They do have to be added to the proprietary glassfish-web.xml role mapping.

**Comment by rdebusscher** [comment]
In the example, the groups are only coming from the GroupProviderIdentityStore, LDAP is just used to 'Validate' the Credentials.

**Comment by arjantijms** [comment]
Indeed, but perhaps by giving the LDAP groups another name it can be made more clear to the person reading the test code and seeing the output that there are indeed no groups coming from LDAP.

**Comment by ggam** [comment]
@rdebusscher Is this still an issue after your https://github.com/javaee/security-soteria/commit/d2a9d30027d6241f2ac89d8d1b09805a1df994f3 commit? What's exactly left to do?

**Comment by rdebusscher** [comment]
@ggam If I remember correctly, the commit solved the issue but there could be another test cases created for some scenarios.
Also, the remark of Arjan isn't implemented to make it more clear from where the groups are retrieved.
But since this is test code, I guess it isn't a high priority.

**Comment by wmhopkins** [comment]
I discovered the `DefaultIdentityStoreHandler` had a similar problem -- didn't remember an _INVALID_ result, and returned _INVALID_ instead of _NOT_VALIDATED_ when no `IdentityStore` handled the credential. Fixed by #171.
