### ISSUE TITLE
Properties are hardcode in Ldap/DatabaseIdentityStoreDefinition Annotation in java code

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#76]
For example, we can use LdapIdentityStore annotation as below, 
@LdapIdentityStoreDefinition(
   url = "ldap://localhost:1389/",
   callerBaseDn = "ou=caller,dc=jsr375,dc=net",
   groupBaseDn  = "ou=group,dc=jsr375,dc=net"
)

The ldap url and other properties are not configurable, and we have to write hardcode in the annotation in the java code. 
Then I am wondering once the ldap server is changed, we have to change the  java source code. Right?
 
My Issue: Is it possible to make it configurable in a configuration file instead of hardcode in annotation?

Thanks!

**Comment by ggam** [comment]
I'm with you in that hardcoding is a bit unconvenient, but I think this is a big problem that will (hopefully) be addressed at spec level on Java EE 9 with a new Configuration JSR.

For the moment, most application servers already support property substitution (see e.g. Payara: https://payara.gitbooks.io/payara-server/content/documentation/core-documentation/configuration/var-substitution/usage-of-variables.html) and I think the RI should also support it as a vendor specific feature.

**Comment by wxwesther** [comment]
Thanks ggmm!

According to your suggestion, I set below jvm options  and restart glassfish server,
bin/asadmin create-jvm-options '-DLDAP_URL=ldap\://localhost\:11389/

Then I change the annotation to:
@ldapidentitystoredefinition(
url = "${LDAP_URL}",
callerBaseDn = "ou=caller,dc=jsr375,dc=net",
groupBaseDn = "ou=group,dc=jsr375,dc=net"
)

But unfortunately, it doesn't work. It seems the implementation of annotation doesn't support to get the system property from JVM.

**Comment by arjantijms** [comment]
Indeed, this would have depended on the Java EE configuration API which was in scope for Java EE 8, but then vanished again.

An other option would be an entry in the default deployment descriptors (web.xml etc) or a separate descriptor for the security api (say WEB-INF/security.xml), but both options do not (via the EE standard) allow you to truly externalise settings, which is what people most of the time really want.

We talked a little about a soteria-extras project of some kind, which is RI specific, but where we put in some extras such as indeed support for external configuration.

>But unfortunately, it doesn't work. It seems the implementation of annotation doesn't support to get the system property from JVM.

Indeed this doesn't work by default.

Payara already supports placeholders in (Java EE) annotations (and descriptors), which I'll probably extend in Payara 5 to support the Java EE Security API annotations.

**Comment by wmhopkins** [comment]
This issue is addressed by the addition of support for EL expressions in attribute values. Spec and API have been updated, and EL support in the RI is mostly done. Leaving the issue open for now, it can be closed when RI support for all annotations is confirmed.

**Comment by wmhopkins** [comment]
Support for EL on all annotations has been implemented.

**Comment by hijakebye** [comment]
Looks like there is no hookpoints to include anything on the ELProcessor you guys are using, how are we supposed to use EL to delegate ? Can you guys do a sample of delegating to some java bean for password or something using EL ? the 3.0 EL APIs typically involve importing classes/functions to be useful

**Comment by ggam** [comment]
EL expressions have access to any defined @Named bean. Does that fit your
goal?
