### ISSUE TITLE
Which type of credential is supported by DatabaseIdentityStore /LDAPIdentityStore in validate() method

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#82]
As you know, there are several kind of credentails, 
UsernamePasswordCredential
BasicAuthenticationCredential
CallerOnlyCredential
RememberMeCredential

I am not sure which types are supported in DatabaseIdentityStore  and LDAPIdentityStore ?

**Comment by rdebusscher** [comment]
Only UsernamePasswordCredential is supported. The other types are defined for other 'ways' of authentication.

**Comment by ggam** [comment]
Hi @rdebusscher is that specified somewhere? I can't find which credential types are required to work for the provided identity stores. Adding a line to the spec might be helpful.

**Comment by rdebusscher** [comment]
Seems not specified yet,

@ggam  Can you send a mail to the javaee-security-spec at javaee.groups.io list to ask for an update of the spec document?

My opinion is that there should be something mentioned like

> the Default Database and LDAP Identity Stores needs to support at least the _UsernamePasswordCredential_.

**Comment by arjantijms** [comment]
Would indeed be good to specify. The stores have been designed to that other types of credentials can be added later.

There was a request of some kind by Will open to at least add support for the CallerOnlyCredential to each store, which would not require API changes, but for which it indeed would be good to have something in the spec.

**Comment by wmhopkins** [comment]
This issue is tracked by javaee/security-spec#42, closing this issue.
