### ISSUE TITLE
Server Exception when set invalid property for DataBaseIdentityStore

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#84]
Set invalid value for dataSourceLookup,  or callerQuery, or groupsQuery,  then validatation got exception and no result (neither INVALID nor VALID / NOT_INVALIDATED returned)

For example:
@DataBaseIdentityStoreDefinition(	    
	   dataSourceLookup="jdbc/invalid",
	    callerQuery="select password from caller where name = ?",
	    groupsQuery="select group_name from caller_groups where caller_name = ?"
)

@DataBaseIdentityStoreDefinition(	    
	   dataSourceLookup="jdbc/securityAPIDB",
	    callerQuery="select invalid from caller where name = ?",
	    groupsQuery="select group_name from caller_groups where caller_name = ?"
)

@DataBaseIdentityStoreDefinition(	    
	   dataSourceLookup="jdbc/securityAPIDB",
	    callerQuery="select password from caller where name = ?",
	    groupsQuery="select invalid from caller_groups where caller_name = ?"
)

[2017-06-20T02:10:11.633-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=29 _ThreadName=Thread-9] [timeMillis: 1497949811633] [levelValue: 1000] [[
  java.lang.IllegalStateException: java.sql.SQLSyntaxErrorException: Column 'INVALID' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'INVALID' is not a column in the target table.
        at org.glassfish.soteria.identitystores.DataBaseIdentityStore.executeQuery(DataBaseIdentityStore.java:135)
        at org.glassfish.soteria.identitystores.DataBaseIdentityStore.validate(DataBaseIdentityStore.java:89)
        at org.glassfish.soteria.identitystores.DataBaseIdentityStore.validate(DataBaseIdentityStore.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by wmhopkins** [comment]
This is working as designed. Although there is an omission in the spec, the validate() method throws an exception when there is an error. Since it wasn't correctly configured, there is an internal error, and a Runtime exception is thrown. A status value is returned only for the three cases identified by the spec -- a VALID credential, an INVALID credential, or a credential that is NOT_VALIDATED because the id store doesn't handle that type of credential. Actual errors -- network errors, config errors, etc. -- are handled by throwing a runtime exception.

This should be documented in the spec and javadoc, but unfortunately isn't. However, the meanings of the status codes are correctly documented.

**Comment by ggam** [comment]
@wmhopkins should we create an issue on the spec tracker for the next version?

**Comment by wmhopkins** [comment]
It's currently tracked in javaee/security-spec#62. If we aren't able to fix it in final edits, it will carry over to a "future updates" issue.

**Comment by wmhopkins** [comment]
Leaving this open now as a reminder to review the DatabaseIdentityStore and how it handles errors.

**Comment by wmhopkins** [comment]
`DatabaseIdentityStore` should use `IdentityStoreConfigurationException` and `IdentityStoreRuntimeException` to signal error conditions.
