### ISSUE TITLE
Querstion about "privileged" and "exception" in spec Section "3.2.2 Retrieving Caller Information"

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#86]
Section "3.2.2 Retrieving Caller Information"  in spec says below.

" Note that getCallerGroups() is not intended as a general purpose API for retrieving user groups. It should be called only by an IdentityStoreHandler, in the course of orchestrating a validate() call across multiple identity stores. IdentityStores should check whether the caller is privileged and throw an exception if not."

I have two questions:  

1. Could you please give me a scenario about "caller is not privileged"?

2. What kind of exception would be thrown?

IMHO, once validation returns VALID in any identityStore, then getCallerGroups() in all the identityStore used for PROVIDE_GROUP only will be called, and no need to verify the caller is privileged anymore.

Any comments? Thanks very much!

**Comment by ggam** [comment]
I think the priviledged part might be removed if we state that calls to
getCallerGroups() are only allowed during an authentication processs and an
exception must be thrown when called from anywhere else (or specify that
behavior is non portable). I think the "it *should* only be called" current
sentence is a bit ambiguous.

On point 2, I don't think the exception type is important, as long as it is
a runtime exception. To me, is like saying "the deployment must fail under
XX circunstances". The important IMHO fact is that it will fail with a
runtime exception, which you are not expected to catch anyway.

**Comment by arjantijms** [comment]
Good catch again.

This is supposed to be a Java SE security manager check. And the JavaDoc for `getCallerGroups` should say something like:

```
    * <P>When a SecurityManager is enabled, this method must confirm that 
     * the calling access control context has been granted the 
     * {@link #callGetCallerGroupsSecurityPermission}
```

And then in the `throws` section:

```
@exception SecurityException If the caller does not have
     	                 permission to call this method
```

However, I personally am not sure this all is needed. IMHO and with all respect it originates from J2EE thinking where the Application Server was seen as a multitasking high level OS running different applications that had to be protected from each other and the Application Server had to be protected from them. Basically the applet model for servers.

But in practice this barely happens. Java EE has never been able to become that operating system, and everyone just runs a single Java EE server in an isolated environment with a single app if those apps are potentially hostile. Almost nobody runs with a Java SE security manager enabled. Real OS processes, containers or even virtual servers (via hypervisor or not) are all much better tools to isolate and protect applications.

In that sense Java EE has been moving much more to being a library, and there's little usage for trying to protect that library against the apps that use it.

**Comment by wmhopkins** [comment]
I think the intent was to prevent an app, or malicious user code that could be injected to run with application or user-level privileges, from being able to directly access a back-end store. While Arjan has a point that Java EE is often used as a library now, there are still lots of enterprise deployments where that type of access shouldn't be allowed.

Unfortunately, given the design we have, we can't dictate what a user implementation of an interface does. We can only suggest that the author should protect against calls by unauthorized code/users. I don't think we want to constrain the implementation to use Java Permissions, although that's certainly the natural mechanism for many implementations to choose.

**Comment by wmhopkins** [comment]
This language has been updated, and specific behavior prescribed. See FAB version of the spec, and the javadoc for `IdentityStore.getCallerGroups()`, `IdentityStoreHandler`, and `IdentityStorePermission`.
